### ISSUE TITLE
Objective-C Version?

### ISSUE THREAD

**Issue by inPhilly** [dbettermann/DBAlertController#1]
This is not an issue but a request - for an objective-c version! This looks awesome. I'd love to be able to use it but I don't know Swift.

**Comment by dbettermann** [comment]
Sure. I'll post back when it's done.

**Comment by inPhilly** [comment]
Incredible - thank you so much!

**Comment by dbettermann** [comment]
Let me know if this works for you. I haven't had a chance to do much testing, but it's functionally equivalent to the Swift version.

https://github.com/dbettermann/AlertController

**Comment by inPhilly** [comment]
Dylan,Thank you so much! I added it to my project and made the appropriate changes. It seems to be working so far (for AlertView, not ActionSheet since that has to be presented from a view). I will shoot you an email if I encounter any issues, but if you don't hear from me, assume all is well. Thank you again so much!Jennifer 

```
 On Tuesday, June 23, 2015 11:10 PM, Dylan Bettermann <notifications@github.com> wrote:
```

 Let me know if this works for you. I haven't had a chance to do much testing, but it's functionally equivalent to the Swift version.https://github.com/dbettermann/AlertController—
