### ISSUE TITLE
Extra window remains when using addTextFieldWithConfigurationHandler

### ISSUE THREAD

**Issue by joeboyscout04** [dbettermann/DBAlertController#11]
I tried to use this in my project but ran into an issue when the text field is used.  If I type in the text field, and then get the text from the text field in the submit handler, the alert dismisses but the window remains and my app behaves as non-functional (I can't tap anything because the window is on top).

**Comment by dbettermann** [comment]
I haven't really used text fields with a `UIAlertController` before, so I'll have to write some code to reproduce your issue.

Do you have a strong reference to your `UIAlertController`? If so, the internal `UIWindow` will not be dismissed. I'm counting on the alert being the only strong reference to the window, so when the alert is released the window is released with it.

**Comment by joeboyscout04** [comment]
Here's the code I'm using:

``` obj-c
    DBAlertController *passwordAlert = [DBAlertController alertControllerWithTitle:@"Enter Password" message:@"Please enter your password",nil) preferredStyle:UIAlertControllerStyleAlert];

    [passwordAlert addTextFieldWithConfigurationHandler:^(UITextField * _Nonnull textField) {
        textField.secureTextEntry = YES;
        textField.placeholder = @"password";
    }];

    UIAlertAction *cancelAction = [UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:^(UIAlertAction * _Nonnull action) {

    }];
    [passwordAlert addAction:cancelAction];

    UIAlertAction *submitAction = [UIAlertAction actionWithTitle:@"Submit" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {

        NSString *password = passwordAlert.textFields.firstObject.text;
        //do something with the password
    }];
    [passwordAlert addAction:submitAction];

    //we don't know where this came from, present it on top.
    [passwordAlert showWithAnimated:YES completion:^{}];
```

It references the alert text field inside the completion handler to get the text of the field.  Does this count as a strong reference?

**Comment by inPhilly** [comment]
I am having the same issue with iOS 9. It happens if I try to access the contents of the textfield at all (even to log them) after the dismissal. This is the only way that the textfield can really be used though... Great control, but this is definitely an issue. Wish I knew how to fix it.

**Comment by dbettermann** [comment]
If you reference the alert within a `UIAlertAction` handler you will get a strong reference cycle.

Here's the solution: http://stackoverflow.com/a/25713688/2088780

**Comment by joeboyscout04** [comment]
OK thanks, I'll try this out.
