### ISSUE TITLE
Add cocoapod

### ISSUE THREAD

**Issue by LookingSharp** [dbettermann/DBAlertController#2]
I see that your readme says cocoapods are coming soon.  Is that underway?

Thanks!

dave

**Comment by dbettermann** [comment]
Hello,

I was holding off until someone requested it. I'll put it in a CocoaPod later today. Just for you ;)

-Dylan

**Comment by LookingSharp** [comment]
Awesome!  Thanks!

**Comment by dbettermann** [comment]
I pushed pod version 0.1.0 to the master repo. Not sure how long it will take to publish.

I'll try it out later today.

**Comment by dbettermann** [comment]
Just tried it out and it works. Let me know if you have any issues.
