### ISSUE TITLE
Support iOS 8 for CocoaPod

### ISSUE THREAD

**Issue by joshjiav5** [dbettermann/DBAlertController#8]
When I was trying to integrate this using CocoaPod with my Framework, the following prompt was introduced

```
[!] Unable to satisfy the following requirements:

- `DBAlertController (~> 0.2.2)` required by `MyFramework (0.1.0)`

Specs satisfying the `DBAlertController (~> 0.2.2)` dependency were found, but they required a higher minimum deployment target.
```

MyFramework has a minimum deployment target of iOS 8

I think all you need to do is change the following, please correct me if I'm wrong

```
  s.platform     = :ios, '9.0'     ->     s.platform     = :ios, '8.0'
```

**Comment by dbettermann** [comment]
0.2.4 has support for iOS 8.

Thanks!
